trigger:
- master

variables:
- name: BUILD_VERSION
  value: 1.4.19

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: 'test'
    projects: 'src/Lavalink4NET.Tests/Lavalink4NET.Tests.csproj'
    arguments: '--configuration Release --no-build'
- task: DotNetCoreCLI@2
  displayName: NuGet packaging
  inputs:
    command: 'pack'
    packagesToPack: 'src/**/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'BUILD_VERSION'
    verbosityPack: Minimal
    verbosityRestore: Minimal
    arguments: '--configuration Release'